name: Deploy Java App to Alibaba Cloud

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build JAR (if needed)
        run: ./mvnw clean package -DskipTests  # 或 ./gradlew bootJar

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/myapp
            # 停止旧进程（根据端口或 jar 名）
            pkill -f myapp.jar || true
            # 删除旧文件
            rm -rf *.jar
            # 上传新 JAR（这里假设你构建在 target/）
            # 注意：SSH action 不能直接传文件，所以我们要在服务器上 git clone + build
            # 更推荐方式：在服务器上拉代码并构建
            git clone https://github.com/code-100-precent/FilmFusion.git
            ./mvnw clean package -DskipTests
            # 启动应用（后台运行）
            nohup java -jar target/*.jar > app.log 2>&1 &
            echo $! > app.pid